openapi: 3.0.0
info:
  title: Products API
  description: API for managing products.
  version: 1.0.0
servers:
  - url: /api
    description: The API server

paths:
  /products:
    get:
      summary: Retrieve all products
      responses:
        '200':
          description: A list of all products
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        price:
                          type: number
                        thumbnail:
                          type: string
                        stock:
                          type: integer

    post:
      summary: Add a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                category:
                  type: string
                thumbnail:
                  type: string
      responses:
        '200':
          description: The created product
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      price:
                        type: number
                      thumbnail:
                        type: string
                      stock:
                        type: integer
                      category:
                        type: string

  /products/{pid}:
    get:
      summary: Retrieve a specific product by ID
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The specified product
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      price:
                        type: number
                      thumbnail:
                        type: string
                      stock:
                        type: integer

    put:
      summary: Update a product by ID
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                price:
                  type: number
                stock:
                  type: integer
                category:
                  type: string
                thumbnail:
                  type: string
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    delete:
      summary: Delete a product by ID
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        category:
          type: string
        thumbnail:
          type: string
