openapi: 3.0.0
info:
  title: Carts API
  description: API documentation for cart management.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server
paths:
  /carts:
    get:
      summary: Get all carts
      responses:
        '200':
          description: List of all carts
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the request
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          description: Cart ID
                        products:
                          type: array
                          items:
                            type: object
                            properties:
                              product:
                                type: object
                                properties:
                                  _id:
                                    type: string
                                    description: Product ID
                                  title:
                                    type: string
                                    description: Product title
                                  price:
                                    type: number
                                    format: float
                                    description: Product price
                              quantity:
                                type: integer
                                description: Quantity of the product
    post:
      summary: Add a new cart
      responses:
        '200':
          description: Cart added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the request
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: Cart ID

  /carts/{cid}:
    get:
      summary: Get a cart by ID
      parameters:
        - name: cid
          in: path
          required: true
          description: Cart ID
          schema:
            type: string
      responses:
        '200':
          description: Cart details
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the request
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: Cart ID
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            product:
                              type: object
                              properties:
                                _id:
                                  type: string
                                  description: Product ID
                                title:
                                  type: string
                                  description: Product title
                                price:
                                  type: number
                                  format: float
                                  description: Product price
                            quantity:
                              type: integer
                              description: Quantity of the product
        '400':
          description: Error retrieving cart

    delete:
      summary: Delete a cart by ID
      parameters:
        - name: cid
          in: path
          required: true
          description: Cart ID
          schema:
            type: string
      responses:
        '200':
          description: Cart deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the request
                  message:
                    type: string
                    description: Success message
        '400':
          description: Error deleting cart

  /carts/{cid}/products/{pid}:
    post:
      summary: Add a product to a cart
      parameters:
        - name: cid
          in: path
          required: true
          description: Cart ID
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: Product ID
          schema:
            type: string
      responses:
        '200':
          description: Product added to cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the request
                  payload:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: Cart ID
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            product:
                              type: object
                              properties:
                                _id:
                                  type: string
                                  description: Product ID
                                title:
                                  type: string
                                  description: Product title
                                price:
                                  type: number
                                  format: float
                                  description: Product price
                            quantity:
                              type: integer
                              description: Quantity of the product
        '400':
          description: Error adding product to cart

    delete:
      summary: Remove a product from a cart
      parameters:
        - name: cid
          in: path
          required: true
          description: Cart ID
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: Product ID
          schema:
            type: string
      responses:
        '200':
          description: Product removed from cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the request
                  message:
                    type: string
                    description: Success message
        '400':
          description: Error removing product from cart

  /carts/{cid}/checkout:
    get:
      summary: Checkout the cart
      parameters:
        - name: cid
          in: path
          required: true
          description: Cart ID
          schema:
            type: string
      responses:
        '200':
          description: Cart checkout details
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: Title of the view
                  cart:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: Cart ID
                      products:
                        type: array
                        items:
                          type: object
                          properties:
                            product:
                              type: object
                              properties:
                                _id:
                                  type: string
                                  description: Product ID
                                title:
                                  type: string
                                  description: Product title
                                price:
                                  type: number
                                  format: float
                                  description: Product price
                            quantity:
                              type: integer
                              description: Quantity of the product
                  amount:
                    type: number
                    format: float
                    description: Total amount of the cart
        '400':
          description: Error retrieving checkout information

  /carts/{cid}/purchase:
    get:
      summary: Purchase items in the cart
      parameters:
        - name: cid
          in: path
          required: true
          description: Cart ID
          schema:
            type: string
      responses:
        '200':
          description: Ticket and not processed items
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: Title of the view
                  ticket:
                    type: string
                    description: Ticket ID
                  notProcessed:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                          description: Product title
                        price:
                          type: number
                          format: float
                          description: Product price
        '400':
          description: Error generating ticket