openapi: 3.0.0
info:
  title: Carts API
  description: API for managing shopping carts and tickets.
  version: 1.0.0
servers:
  - url: /api
    description: The API server

paths:
  /carts:
    get:
      summary: Retrieve all carts
      responses:
        '200':
          description: A list of all carts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The unique identifier of the cart
                    products:
                      type: array
                      items:
                        type: object
                        properties:
                          productId:
                            type: string
                          quantity:
                            type: integer

    post:
      summary: Create a new cart
      responses:
        '200':
          description: The created cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        productId:
                          type: string
                        quantity:
                          type: integer

  /carts/{cid}:
    get:
      summary: Retrieve products from a specific cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Products in the specified cart
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      type: object
                      properties:
                        productId:
                          type: string
                        quantity:
                          type: integer

    delete:
      summary: Delete all products from a specific cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: string

    put:
      summary: Update product quantity in a specific cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Updated cart information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object

  /carts/{cid}/products/{pid}:
    post:
      summary: Add a product to a specific cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object

    delete:
      summary: Remove a product from a specific cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object

    put:
      summary: Update the quantity of a specific product in a specific cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        '200':
          description: Updated cart information
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object

  /carts/{cid}/checkout:
    get:
      summary: Render checkout view
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Checkout view page
          content:
            text/html:
              schema:
                type: string

  /carts/{cid}/purchase:
    post:
      summary: Complete the purchase of the items in the cart
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Purchase completion confirmation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object

  /carts/{cid}/purchase:
    get:
      summary: Retrieve purchase details and ticket information
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ticket information page
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer

    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        price:
          type: number
        stock:
          type: integer
